### ISSUE TITLE
dom4j is flagged by OWASP dependency check

### ISSUE THREAD

**Issue by reestolonio** [PAXSTORE/paxstore-3rd-app-java-sdk#3]
https://github.com/PAXSTORE/paxstore-3rd-app-java-sdk/blob/462c0448af5faca6033d6a4995b88eced5446931/app-java-sdk/build.gradle#L7

This version of `dom4j` is flagged by OWASP dependency check.
[issue](https://nvd.nist.gov/vuln/search/results?form_type=Advanced&results_type=overview&search_type=all&cpe_vendor=cpe%3A%2F%3Adom4j_project&cpe_product=cpe%3A%2F%3Adom4j_project%3Adom4j&cpe_version=cpe%3A%2F%3Adom4j_project%3Adom4j%3A1.6.1)

See [this gradle plugin tool](https://jeremylong.github.io/DependencyCheck/dependency-check-gradle/index.html)

**Comment by Apollolight** [comment]
Already updated to 2.1.3
